[package]
name = "phd-template"
version = "0.2.4"
entrypoint = "src/lib.typ"
authors = ["Dimitri Kokkonis (kokkonisd@gmail.com)"]
license = "Unlicense"
description = "A template for documents & presentations relating to my PhD."
