[package]
name = "cea-template"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["Dimitri Kokkonis (kokkonisd@gmail.com)"]
license = "Unlicense"
description = "A template for CEA documents & presentations."
