[package]
name = "phd-template"
version = "0.2.0dev"
entrypoint = "template.typ"
authors = ["Dimitri Kokkonis (kokkonisd@gmail.com)"]
license = "Unlicense"
description = "A template for documents & presentations relating to my PhD."
